In [22]:
# Create a constant array
# Prints "[[ 7.  7.]
#[ 7.  7.]]"            

import numpy as np 
x=np.array([[7. , 7.],[7. ,7.]])   
print(x)           

[[7. 7.]
 [7. 7.]]


In [23]:
# Create an array filled with random values
# Might print "[[ 0.91940167  0.08143941]
#               [ 0.68744134  0.87236687]]"
import numpy as np
x = np.random.rand(2, 2)
print(x)


[[0.3419154  0.76555084]
 [0.20301394 0.84269176]]


In [16]:
# 3. Create a NumPy array containing the numbers from 10 to 50.
# Display: the array, number of elements, shape, dimension, and data type

import numpy as np
arr = np.arange(10, 51)

print("The array:", arr)
print("Number of elements:", arr.size)
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Data type:", arr.dtype)


The array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Number of elements: 41
Shape: (41,)
Dimension: 1
Data type: int64


In [25]:
#4. Using NumPy, create:
#A 1D array containing 10 zeros
#A 3 × 3 array containing ones
#A 4 × 4 identity matrix
#An array containing numbers from 5 to 50 with a step size of 5.
import numpy as np
zero=np.zeros(10)
identity=np.eye(4,4)
ones=np.ones(3)
m=np.arange(5,51,5)
print(zero)
print(identity)
print(ones)
print(m)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1. 1. 1.]
[ 5 10 15 20 25 30 35 40 45 50]


In [30]:
#5. Create an array containing numbers from 1 to 24. Reshape it into:
#4 × 6
#6 × 4
#2 × 3 × 4
#Display the shape and ndim of each result.
import numpy as np
array=np.arange(1,25)
print(array)
m=array.reshape(4,6)
print(m)
print(m.ndim)
n=array.reshape(6,4)
print(n)
print(n.ndim)
o=array.reshape(2,3,4)
print(o)
print(o.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
2
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
3


In [38]:
#6. Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
#Write NumPy statements to display:
#First element
#Last element
#Third element
#First four elements
#Last three elements

marks=np.array([78, 85, 92, 67, 88, 73, 95, 81])
print(marks[0])
print(marks[-1])
print(marks[2])
print(marks[0:4])
print(marks[-4:-1])

78
81
92
[78 85 92 67]
[88 73 95]


In [41]:
#7. Create:
#a = np.array([10, 20, 30, 40, 50])
#b = np.array([5, 10, 15, 20, 25])
#Calculate:
#a + b
#a - b
#a * b
#a / b
#Square of every element in a

a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

[15 30 45 60 75]
[ 5 10 15 20 25]
[  50  200  450  800 1250]
[2. 2. 2. 2. 2.]
[ 100  400  900 1600 2500]


In [49]:
#8. Given:
#salary = np.array([25000, 32000, 28000, 45000,50000, 38000, 42000, 30000])
#Find:
#Total salary
#Average salary
#Highest salary
#Lowest salary
#Median salary
#Standard deviation

import numpy as np

salary = np.array([25000, 32000, 28000, 45000, 50000, 38000, 42000, 30000])

print(salary.sum())
print(salary.mean())
print(salary.max())
print(salary.min())
print(np.median(salary))
print(salary.std())

290000
36250.0
50000
25000
35000.0
8317.902379807063


In [50]:

#9. Given: marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])
#Using NumPy boolean indexing, find:
#Marks greater than 75
#Marks between 50 and 80
#Number of students who scored below 50
#Percentage of students who scored 60 or above
#Do not use a Python for loop.


import numpy as np

marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])

greater_than_75 = marks > 75
between_50_and_80 = (marks >= 50) & (marks <= 80)
below_50 = marks < 50
score_60_or_above = marks >= 60

print(marks[greater_than_75])
print(marks[between_50_and_80])
print(np.count_nonzero(below_50))
print((np.count_nonzero(score_60_or_above) / len(marks)) * 100)

[78 89 90 76 84]
[78 67 55 76]
3
60.0


In [ ]:

#10. The following array contains marks of four students in three subjects:
#marks = np.array([
#    [80, 75, 90],
#    [65, 70, 72],
##   [55, 60, 58]
#])

#Calculate:

#Total marks of each student
#Average marks of each student
#Average marks in each subject
#Student with the highest total
#Highest mark in each subject.


marks = np.array([
   [80, 75, 90],
   [65, 70, 72],
   [55, 60, 58]
])

print("total marks of each student",np.sum(marks,axis=1))
print("average marks of each student",np.mean(marks,axis=1))
print("average marks of each student",np.mean(marks,axis=0))
print("student with highest total ",np.max(marks,axis=1))
print("student with highest marks",np.max(marks,axis=0))

total marks of each student [245 207 173]
average marks of each student [81.66666667 69.         57.66666667]
average marks of each student [66.66666667 68.33333333 73.33333333]
student with highest total  [90 72 60]
student with highest marks [80 75 90]


In [1]:

# 11. Create:

# A = np.array([
#     [1, 2],
#     [3, 4]
# ])

# B = np.array([
#     [5, 6],
#     [7, 8]
# ])

# Perform:

# Matrix addition
# Element-wise multiplication
# Matrix multiplication
# Transpose of A.

# explain the difference between:
# A * B and A @ B

import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("A + B =")
print(A + B)

print("\nA * B (element-wise multiplication) =")
print(A * B)

print("\nA @ B (matrix multiplication) =")
print(A @ B)

print("\nTranspose of A =")
print(A.T)

print("\nDifference between A * B and A @ B:")
print("A * B multiplies matching elements position by position.")
print("A @ B performs matrix multiplication using dot products of rows and columns.")
print("So, A * B keeps the same shape as A and B, while A @ B follows matrix multiplication rules and requires compatible dimensions.")

A + B =
[[ 6  8]
 [10 12]]

A * B (element-wise multiplication) =
[[ 5 12]
 [21 32]]

A @ B (matrix multiplication) =
[[19 22]
 [43 50]]

Transpose of A =
[[1 3]
 [2 4]]

Difference between A * B and A @ B:
A * B multiplies matching elements position by position.
A @ B performs matrix multiplication using dot products of rows and columns.
So, A * B keeps the same shape as A and B, while A @ B follows matrix multiplication rules and requires compatible dimensions.


In [2]:
# 12. Daily temperatures for two weeks are:

# temperature = np.array([
#     31, 32, 33, 35, 36, 34, 32,
#     30, 29, 31, 33, 35, 37, 36
# ])

# Find:

# Mean temperature
# Maximum and minimum temperatures
# Number of days above the average temperature
# Temperatures greater than 34°C
# Difference between maximum and minimum
# Standard deviation

import numpy as np

temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])

mean_temp = temperature.mean()
max_temp = temperature.max()
min_temp = temperature.min()
above_avg = temperature[temperature > mean_temp]
above_34 = temperature[temperature > 34]
diff = max_temp - min_temp
std_dev = temperature.std()

print("Mean temperature:", mean_temp)
print("Maximum temperature:", max_temp)
print("Minimum temperature:", min_temp)
print("Number of days above average:", len(above_avg))
print("Temperatures greater than 34°C:", above_34)
print("Difference between maximum and minimum:", diff)
print("Standard deviation:", std_dev)

Mean temperature: 33.142857142857146
Maximum temperature: 37
Minimum temperature: 29
Number of days above average: 6
Temperatures greater than 34°C: [35 36 35 37 36]
Difference between maximum and minimum: 8
Standard deviation: 2.356060357495806


In [3]:
# 13. Monthly sales of a company are:
# sales = np.array([
#     12000, 15000, 17000, 14000,
#     18000, 21000, 19000, 22000,
#     25000, 23000, 26000, 28000
# ])

# Determine:

# Total annual sales
# Average monthly sales
# Month with the highest sales
# Month with the lowest sales
# Number of months with sales above ₹20,000
# Percentage increase from January to December

# Hint: Remember that NumPy indexing starts at 0, while month numbering normally starts at 1.

import numpy as np

sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])

# Total annual sales
annual_total = sales.sum()

# Average monthly sales
average_sales = sales.mean()

# Month with the highest sales
highest_index = sales.argmax()
highest_month = highest_index + 1  # convert 0-based index to 1-based month number

# Month with the lowest sales
lowest_index = sales.argmin()
lowest_month = lowest_index + 1

# Number of months with sales above ₹20,000
above_20000 = sales[sales > 20000]
count_above_20000 = len(above_20000)

# Percentage increase from January to December
january = sales[0]
december = sales[-1]
percentage_increase = ((december - january) / january) * 100

print("Total annual sales:", annual_total)
print("Average monthly sales:", average_sales)
print("Month with the highest sales:", highest_month)
print("Month with the lowest sales:", lowest_month)
print("Number of months with sales above ₹20,000:", count_above_20000)
print("Percentage increase from January to December:", percentage_increase, "%")

Total annual sales: 240000
Average monthly sales: 20000.0
Month with the highest sales: 12
Month with the lowest sales: 1
Number of months with sales above ₹20,000: 6
Percentage increase from January to December: 133.33333333333331 %


In [4]:

# 14. Consider marks of five students in four subjects:

# marks = np.array([
#     [78, 85, 90, 88],
#     [65, 70, 72, 68],
#     [92, 88, 95, 91],
#     [55, 60, 58, 62],
#     [80, 75, 82, 79]
# ])

# Write a NumPy program that calculates:

# Total marks of every student
# Average of every student
# Average mark for every subject
# Highest-scoring student
# Lowest-scoring student
# Students whose average is greater than 80
# Overall class average

# Then assign a performance category based on average:

# |  Average | Category          |
# | -------: | ----------------- |
# |     ≥ 85 | Excellent         |
# | 70–84.99 | Good              |
# | 50–69.99 | Average           |
# |     < 50 | Needs Improvement |

# Challenge: Try assigning these categories using np.where() or np.select() instead of a Python loop.

import numpy as np

marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])

student_totals = marks.sum(axis=1)
student_averages = marks.mean(axis=1)
subject_averages = marks.mean(axis=0)

highest_student = np.argmax(student_averages) + 1
lowest_student = np.argmin(student_averages) + 1
students_above_80 = np.where(student_averages > 80)[0] + 1
overall_class_average = marks.mean()

print("Total marks of every student:", student_totals)
print("Average of every student:", student_averages)
print("Average mark for every subject:", subject_averages)
print("Highest-scoring student:", highest_student)
print("Lowest-scoring student:", lowest_student)
print("Students whose average is greater than 80:", students_above_80)
print("Overall class average:", overall_class_average)

# Performance category using np.select()
conditions = [
    student_averages >= 85,
    (student_averages >= 70) & (student_averages < 85),
    (student_averages >= 50) & (student_averages < 70),
    student_averages < 50
]
labels = ["Excellent", "Good", "Average", "Needs Improvement"]
performance_categories = np.select(conditions, labels, default="Needs Improvement")

print("Performance categories:", performance_categories)

Total marks of every student: [341 275 366 235 316]
Average of every student: [85.25 68.75 91.5  58.75 79.  ]
Average mark for every subject: [74.  75.6 79.4 77.6]
Highest-scoring student: 3
Lowest-scoring student: 4
Students whose average is greater than 80: [1 3]
Overall class average: 76.65
Performance categories: ['Excellent' 'Average' 'Excellent' 'Average' 'Good']


In [5]:
# 15. Generate 20 random integers between 1 and 100.

import numpy as np

random_integers = np.random.randint(1, 101, size=20)
print(random_integers)

[88  4 32 49 36 42 64 45 19 84 97 74 35 49 76 80 14 24 32 94]


In [6]:
# 16. Find all even numbers from the generated array.

import numpy as np

random_integers = np.random.randint(1, 101, size=20)
print("Generated array:", random_integers)
print("Even numbers:", random_integers[random_integers % 2 == 0])

Generated array: [47 91 81 46 73 82 63  7 21 50 30 76 18 67 95 82  1 95 51  8]
Even numbers: [46 82 50 30 76 18 82  8]


In [7]:
# 17. Replace values below 50 with 0.

import numpy as np

random_integers = np.random.randint(1, 101, size=20)
print("Original array:", random_integers)

random_integers[random_integers < 50] = 0
print("After replacing values below 50 with 0:", random_integers)

Original array: [  4  79  96  27  52  97  59  71  29  70  93  25  87  13  26  45  81  20
 100   9]
After replacing values below 50 with 0: [  0  79  96   0  52  97  59  71   0  70  93   0  87   0   0   0  81   0
 100   0]


In [8]:
# 18. Sort the array in ascending and descending order.

import numpy as np

arr = np.array([9, 3, 7, 1, 5, 8, 2, 6, 4])

ascending = np.sort(arr)
descending = np.sort(arr)[::-1]

print("Original array:", arr)
print("Ascending order:", ascending)
print("Descending order:", descending)

Original array: [9 3 7 1 5 8 2 6 4]
Ascending order: [1 2 3 4 5 6 7 8 9]
Descending order: [9 8 7 6 5 4 3 2 1]


In [9]:
# 19. Find unique values and their frequencies.

import numpy as np

arr = np.array([5, 2, 5, 3, 2, 5, 7, 3, 7, 2, 9])
unique_values, counts = np.unique(arr, return_counts=True)

print("Unique values:", unique_values)
print("Frequencies:", counts)

for value, count in zip(unique_values, counts):
    print(f"Value {value} appears {count} times")

Unique values: [2 3 5 7 9]
Frequencies: [3 2 3 2 1]
Value 2 appears 3 times
Value 3 appears 2 times
Value 5 appears 3 times
Value 7 appears 2 times
Value 9 appears 1 times


In [1]:
# 20. Create a 5 × 5 random matrix and calculate row-wise and column-wise means.

import numpy as np

matrix = np.random.rand(5, 5)
row_means = matrix.mean(axis=1)
col_means = matrix.mean(axis=0)

print("Random 5x5 matrix:\n", matrix)
print("\nRow-wise means:", row_means)
print("Column-wise means:", col_means)

Random 5x5 matrix:
 [[0.02175327 0.938675   0.44457279 0.91070181 0.50575893]
 [0.02297061 0.34946758 0.58047712 0.43394125 0.41589268]
 [0.69881443 0.84253657 0.67988953 0.61663104 0.86613536]
 [0.8448447  0.29239233 0.29932537 0.3608695  0.24334135]
 [0.64646999 0.96462577 0.46851128 0.93145325 0.06128939]]

Row-wise means: [0.56429236 0.36054985 0.74080139 0.40815465 0.61446993]
Column-wise means: [0.4469706  0.67753945 0.49455522 0.65071937 0.41848354]


In [3]:
# 21. Take your own example to normalize an array.  
import numpy as np

# Own example array
arr = np.array([10, 20, 30, 40, 50])

# Minimum and maximum values
min_val = arr.min()
max_val = arr.max()

# Min-Max normalization formula
normalized = (arr - min_val) / (max_val - min_val)

print("Original array:", arr)
print("Normalized array:", normalized)

Original array: [10 20 30 40 50]
Normalized array: [0.   0.25 0.5  0.75 1.  ]
