In [22]:
# Create a constant array
# Prints "[[ 7.  7.]
#[ 7.  7.]]"            

import numpy as np 
x=np.array([[7. , 7.],[7. ,7.]])   
print(x)           

[[7. 7.]
 [7. 7.]]


In [23]:
# Create an array filled with random values
# Might print "[[ 0.91940167  0.08143941]
#               [ 0.68744134  0.87236687]]"
import numpy as np
x = np.random.rand(2, 2)
print(x)


[[0.3419154  0.76555084]
 [0.20301394 0.84269176]]


In [16]:
# 3. Create a NumPy array containing the numbers from 10 to 50.
# Display: the array, number of elements, shape, dimension, and data type

import numpy as np
arr = np.arange(10, 51)

print("The array:", arr)
print("Number of elements:", arr.size)
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Data type:", arr.dtype)


The array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Number of elements: 41
Shape: (41,)
Dimension: 1
Data type: int64


In [25]:
#4. Using NumPy, create:
#A 1D array containing 10 zeros
#A 3 × 3 array containing ones
#A 4 × 4 identity matrix
#An array containing numbers from 5 to 50 with a step size of 5.
import numpy as np
zero=np.zeros(10)
identity=np.eye(4,4)
ones=np.ones(3)
m=np.arange(5,51,5)
print(zero)
print(identity)
print(ones)
print(m)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1. 1. 1.]
[ 5 10 15 20 25 30 35 40 45 50]


In [30]:
#5. Create an array containing numbers from 1 to 24. Reshape it into:
#4 × 6
#6 × 4
#2 × 3 × 4
#Display the shape and ndim of each result.
import numpy as np
array=np.arange(1,25)
print(array)
m=array.reshape(4,6)
print(m)
print(m.ndim)
n=array.reshape(6,4)
print(n)
print(n.ndim)
o=array.reshape(2,3,4)
print(o)
print(o.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
2
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
3


In [38]:
#6. Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
#Write NumPy statements to display:
#First element
#Last element
#Third element
#First four elements
#Last three elements

marks=np.array([78, 85, 92, 67, 88, 73, 95, 81])
print(marks[0])
print(marks[-1])
print(marks[2])
print(marks[0:4])
print(marks[-4:-1])

78
81
92
[78 85 92 67]
[88 73 95]


In [41]:
#7. Create:
#a = np.array([10, 20, 30, 40, 50])
#b = np.array([5, 10, 15, 20, 25])
#Calculate:
#a + b
#a - b
#a * b
#a / b
#Square of every element in a

a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

[15 30 45 60 75]
[ 5 10 15 20 25]
[  50  200  450  800 1250]
[2. 2. 2. 2. 2.]
[ 100  400  900 1600 2500]


In [49]:
#8. Given:
#salary = np.array([25000, 32000, 28000, 45000,50000, 38000, 42000, 30000])
#Find:
#Total salary
#Average salary
#Highest salary
#Lowest salary
#Median salary
#Standard deviation

import numpy as np

salary = np.array([25000, 32000, 28000, 45000, 50000, 38000, 42000, 30000])

print(salary.sum())
print(salary.mean())
print(salary.max())
print(salary.min())
print(np.median(salary))
print(salary.std())

290000
36250.0
50000
25000
35000.0
8317.902379807063


In [50]:

#9. Given: marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])
#Using NumPy boolean indexing, find:
#Marks greater than 75
#Marks between 50 and 80
#Number of students who scored below 50
#Percentage of students who scored 60 or above
#Do not use a Python for loop.


import numpy as np

marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])

greater_than_75 = marks > 75
between_50_and_80 = (marks >= 50) & (marks <= 80)
below_50 = marks < 50
score_60_or_above = marks >= 60

print(marks[greater_than_75])
print(marks[between_50_and_80])
print(np.count_nonzero(below_50))
print((np.count_nonzero(score_60_or_above) / len(marks)) * 100)

[78 89 90 76 84]
[78 67 55 76]
3
60.0


In [52]:

#10. The following array contains marks of four students in three subjects:
#marks = np.array([
#    [80, 75, 90],
#    [65, 70, 72],
##   [55, 60, 58]
#])

#Calculate:

#Total marks of each student
#Average marks of each student
#Average marks in each subject
#Student with the highest total
#Highest mark in each subject.


marks = np.array([
   [80, 75, 90],
   [65, 70, 72],
   [55, 60, 58]
])

print("total marks of each student",np.sum(marks,axis=1))
print("average marks of each student",np.mean(marks,axis=1))
print("average marks of each student",np.mean(marks,axis=0))
print("student with highest total ",np.max(marks,axis=1))
print("student with highest marks",np.max(marks,axis=0))

total marks of each student [245 207 173]
average marks of each student [81.66666667 69.         57.66666667]
average marks of each student [66.66666667 68.33333333 73.33333333]
student with highest total  [90 72 60]
student with highest marks [80 75 90]
