In [3]:
import numpy  as np
test=np.random.randint(1,10,(4,3))
test

array([[8, 5, 6],
       [4, 7, 2],
       [8, 1, 9],
       [2, 8, 3]])

In [4]:
for i,row in enumerate(test):
    print('row',i,'is',row)

row 0 is [8 5 6]
row 1 is [4 7 2]
row 2 is [8 1 9]
row 3 is [2 8 3]


In [6]:
test2=test**2
test2

array([[64, 25, 36],
       [16, 49,  4],
       [64,  1, 81],
       [ 4, 64,  9]])

In [7]:
for i,j in zip(test,test2):
    print(i,'+',j,'=',i+j)

[8 5 6] + [64 25 36] = [72 30 42]
[4 7 2] + [16 49  4] = [20 56  6]
[8 1 9] + [64  1 81] = [72  2 90]
[2 8 3] + [ 4 64  9] = [ 6 72 12]


In [8]:
marks=np.array([
    [20,25,23],
    [65,25,34],
    [55,43,22]
])

In [9]:
marks

array([[20, 25, 23],
       [65, 25, 34],
       [55, 43, 22]])

In [10]:
student_total=np.sum(marks,axis=1)

In [11]:
student_total

array([ 68, 124, 120])