In [3]:
import numpy as np

In [4]:
#operation
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x)
print(y)
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**2)

[1 2 3]
[4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [5]:
x.dot(y)

np.int64(32)

In [6]:
z=np.array([y,y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [9]:
z.shape

(2, 3)

In [10]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [11]:
len(z)

2

In [12]:
z.T.shape

(3, 2)

In [13]:
z.dtype

dtype('int64')

In [14]:
z=z.astype('f')
z.dtype

dtype('float32')

In [16]:
a=np.array([1,3,5])
a.sum()

np.int64(9)

In [18]:
a.max()

np.int64(5)

In [19]:
a.min()

np.int64(1)

In [20]:
a.mean()

np.float64(3.0)

In [21]:
a.std()

np.float64(1.632993161855452)

In [ ]:
a.argmin()

In [ ]:
import numpy as np
s=np.arange(100)
s